# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties (https://fabricmc.net/develop)
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.5
loader_version=0.19.2
loom_version=1.16.1

# Mod Properties
mod_version=
maven_group=ru.massonnn
archives_base_name=MasUtils
# Dependencies
fabric_version=0.141.4+1.21.11
dandelion_version=1.0.0-alpha.15+1.21.11
mixinconstraints_version=1.1.0
occlusionculling_version=0.0.8-SNAPSHOT
hm_api_version=1.0.2+1.21.11
mod_menu_version = 16.0.0-rc.1
moulconfig_flavour=modern-1.21.7
moulconfig_version=4.0.1-beta

flk_version=1.13.11+kotlin.2.3.21